### ISSUE TITLE
Wordpress XPress theme differs in IE

### ISSUE THREAD

**Issue by RexSeven** [Audentio/xpress-issues#229]
IE seems to render the page as if its on mobile? Tested on two devices. All other browsers it seems fine.
https://i.imgur.com/Chb5X5Z.jpg

**Comment by LukasWieditz** [comment]
Apparently IE11 does not support grid css out of the box. I've added their prefixed versions, now stuff is at least back in columns, but they're not equal height and missing spacing between them.

**Comment by daltonp** [comment]
This is what I'm seeing when viewing with IE 11 -- Looks like the header, author, prefix, edit date, etc is aligned to the right instead of the center. But this maybe relates to what Lukas said above, ignore if it is.
![ie-11-xpress](https://user-images.githubusercontent.com/32306910/44863412-afad7680-ac42-11e8-8308-45a423bf250d.png)
