### ISSUE TITLE
[XPress] Caching recommendation as a blog article on themehouse

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xpress-issues#234]
Due to the complexity of this situation, maybe a guide on how best to approach caching.

- [x] A list of WP add-ons that work well
- [x] Basic guide and rationale for how to approach it (with notifications and other items)
- [x] Any possible server limitation or expected increase in server activity due to XPress

**Comment by LukasWieditz** [comment]
@mikecreuzer can we prioritize this? We keep getting asked this question quite regularly.

**Comment by kylerc** [comment]
I've only worked with Litespeed Cache for this so far, but I'd guess that other caching solutions would likely work too as long as they allow for similar configurations.  The only changes needed should be:

1. Prevent caching when a user has a `xf_user` cookie set since logged in users will have dynamic content.
2. Change the login and register to be a separate page (rather than a modal / dropdown) to have them use a url that can be blacklisted.
3. Blacklist the login and register urls since each of those are dynamically generated for anti-spam and security reasons.

I don't think there should be any server changes as long as the server meets the hardware needs of the caching software.
