### ISSUE TITLE
Dynamic category links in tablinks

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xpress-issues#57]
Wasnt sure which, but UI.X looks fug without anything up there. If nothing else, we can use a wp_nav_menu (https://codex.wordpress.org/Navigation_Menus)

And by default just have like Pages show up there or something.

**Comment by Ian-Hitt** [comment]
@mikecreuzer if nothing else we can just add installation/setup documentation for sub nav?

**Comment by LukasWieditz** [comment]
> Ideal is there is a XenForo navigation item that accepts the wp_nav unique ID or something.

I don't see the value in this? From a user perspective, where's the difference in setting up your subnavigation in WP or XF? From a programming perspective in regards to this first question, it's just unnecessary clutter?

**Comment by LukasWieditz** [comment]
Displaying the categories as fallback now if no subnavigation elements have been defined in XenForo. Still don't see any value to manage this subnavigation element in WP rather than in XenForo, actually I think it's causing more confusion than it offers benefits (does it even offer some?).

@Ian-Hitt the subnavigation elements look different in UI.X but idk what I am missing, unless the markup completely changes in UI.X. Please have a look. Template is `thxpress_subnav`.
