### ISSUE TITLE
index articles in XF for search

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xpress-issues#78]

**Comment by mikecreuzer** [comment]
What does this mean?

**Comment by LukasWieditz** [comment]
As the title says, indexing WordPress articles in XenForo, so we can get rid of the WordPress search, if possible and have a unified search.

**Comment by mikecreuzer** [comment]
idk if you can rely on this. Maybe. You'd need to be aware of add-ons that may modify search. Im not sure off hand. We would at least want a way to keep WP search routes/query.

Regardless I think a unified search page is a good idea (in appearance at least). Will create a new issue.

**Comment by LukasWieditz** [comment]
Closing due to #95

**Comment by KirbyDE** [comment]
I am sorry, but the current implementation is neither seamless nor really integrated:

While it is possible to search for post, media and resources with just one search from the global search box without having to switch to "Seach Forums / Search Media Gallery / Search Resources" this is not possible for XPress - the user has to specifically select "Search Blog" in order to search in WordPress and will only get results from WordPress whereas he will get results from all Add-ons (that properly integrate with XenForo search) when selecting "Search forums".

This is confusing, not userfriendly and bascialy opens a can of worms - image more and more Add-ons "integrating" this way (like it was in vBulletin 3 and partly still in vBulletin 4 as 3rd party authors apparently didn't manage to understand how the system works to integrate their stuff), it would be a recipe for complete mess.

If you really want XPress to become a 1st class citizen in the XenForo eco-system, you really should try to get this done properly as it is IMHO also in conflict with resource [standards rule  # 21](https://xenforo.com/community/help/resource-standards/).

> Add-ons must utilise the various “handler” systems where available to their full extent rather than extending classes to inject custom behaviour. Including, but not limited to, Spam checking which must be implemented using the spam checker handler system rather than extending the checkForSpam methods in different places.

**Comment by LukasWieditz** [comment]
As WordPress with plugins can feature an infinite set of items and content types that can be stored in the WordPress search index, and we have no knowledge when and how they get inserted, it is literally impossible to fully implement this in any other way than currently done. Threatening with resource standards won't overcome this technical limitation either.
